### ISSUE TITLE
我用HRNet32作Backbone时，训练完出现了RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!这个问题

### ISSUE THREAD

**Issue by ChenShuai-CA** [Bobo-y/flexible-yolov5#131]
Traceback (most recent call last):
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/scripts/train.py", line 666, in <module>
    main(opt)
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/scripts/train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/scripts/train.py", line 451, in train
    results, _, _ = eval.run(
  File "/home/shunde/anaconda3/envs/helmet_detect/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/scripts/eval.py", line 187, in run
    out, train_out = model(im) if training else model(im)  # inference, loss outputs
  File "/home/shunde/anaconda3/envs/helmet_detect/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/od/models/model.py", line 71, in forward
    y = self.detection(list(out))
  File "/home/shunde/anaconda3/envs/helmet_detect/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/shunde/Data/chenshuai/HRNet-yolov5/od/models/head/yolo.py", line 44, in forward
    y[..., 0:2] = (y[..., 0:2] * 2 + self.grid[i]) * self.stride[i]  # xy
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
这个问题我看是eval.py里面的问题，请问这个您有办法解决吗？

**Comment by Bobo-y** [comment]
@ChenShuai-CA 训练完后，单独加载权重只执行 eval.py 是可以的. 连在一起报错，我还得查查

**Comment by Bobo-y** [comment]
@ChenShuai-CA done, see https://github.com/Bobo-y/flexible-yolov5/commit/9287ca31322f39fd70156a3bc558946a0eb48540
