### ISSUE TITLE
Quantization error

### ISSUE THREAD

**Issue by ratom** [Bobo-y/flexible-yolov5#159]
I got this error when running the code.
2024-04-06 07:18:16.875938: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-06 07:18:16.875995: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-06 07:18:16.877491: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-06 07:18:18.024997: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/flexible-yolov5/scripts/train.py", line 61, in <module>
    from utils.qat_util import QAT
  File "/content/flexible-yolov5/./utils/qat_util.py", line 4, in <module>
    from torch.ao.pytorch_quantization import quant_modules
ModuleNotFoundError: No module named 'torch.ao.pytorch_quantization'

Moreover I cannot install !pip install scikit-learn==0.19.2   . I am using google colab

**Comment by Bobo-y** [comment]
hi, for quantization, should install pytorch_quantization lib, now I use try exception to wrap this import, if you don't need quantization, there is no influence.
